datasource:
  host: 192.168.192.215
  port: 3306
  username: root
  password: 15833097133duan!
  log_level: dev
logger:
  level: info
  prefix: '[MrArchie]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  log_level: dev